// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// maf_db_reader
CharacterVector maf_db_reader(CharacterVector table_name, CharacterVector text, CharacterVector header, IntegerVector rules, int starting_point);
RcppExport SEXP _rMAFdb_maf_db_reader(SEXP table_nameSEXP, SEXP textSEXP, SEXP headerSEXP, SEXP rulesSEXP, SEXP starting_pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type table_name(table_nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type text(textSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type header(headerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rules(rulesSEXP);
    Rcpp::traits::input_parameter< int >::type starting_point(starting_pointSEXP);
    rcpp_result_gen = Rcpp::wrap(maf_db_reader(table_name, text, header, rules, starting_point));
    return rcpp_result_gen;
END_RCPP
}
// test_MAFdb
CharacterVector test_MAFdb(CharacterVector table_name, CharacterVector text, CharacterVector header, IntegerVector rules, int starting_point);
RcppExport SEXP _rMAFdb_test_MAFdb(SEXP table_nameSEXP, SEXP textSEXP, SEXP headerSEXP, SEXP rulesSEXP, SEXP starting_pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type table_name(table_nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type text(textSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type header(headerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rules(rulesSEXP);
    Rcpp::traits::input_parameter< int >::type starting_point(starting_pointSEXP);
    rcpp_result_gen = Rcpp::wrap(test_MAFdb(table_name, text, header, rules, starting_point));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rMAFdb_maf_db_reader", (DL_FUNC) &_rMAFdb_maf_db_reader, 5},
    {"_rMAFdb_test_MAFdb", (DL_FUNC) &_rMAFdb_test_MAFdb, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rMAFdb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
