# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add priority index
#'
#' Auxiliary function to add a "Priority Index".
#' A priority index follows the db_index number (normally, the MAF line)
#' position and keeps track of the order of the element in the field
#' considered for the split in that row.
#'
#' This is useful for example to maintain priority order of VEP annotations
#' in the MAF file.
#'
#' @param table table on which to add this priority index
#'
#' @return
NULL

#' Prepare queries to store a maf file in a database
#'
#' -- tested with PostgreSQL --
#'
#' @param table_name name of the db table
#' @param text group of maf lines (original text)
#' @param header names of the columns
#' @param rules list of actions to manage fields (quoting)
#' @param starting_point starting index for "db_index" column (primary key)
#'
#' Function exported for R
#' @return the necessary insertion query to load MAF data into a database
#' @export
maf_db_reader <- function(table_name, text, header, rules, starting_point) {
    .Call('_rMAFdb_maf_db_reader', PACKAGE = 'rMAFdb', table_name, text, header, rules, starting_point)
}

#' Test
#'
#' Simple testing procedure used for a small table and to show functionalities
#' (see .Rmd file)
#'
#' @param table_name name of the db table
#' @param text group of maf lines (original text)
#' @param header names of the columns
#' @param rules list of actions to manage fields (quoting)
#' @param starting_point starting index for "db_index" column (primary key)
#'
#' Function exported for R
#' @return the necessary insertion query to load MAF data into a database
#' @export
test_MAFdb <- function(table_name, text, header, rules, starting_point) {
    .Call('_rMAFdb_test_MAFdb', PACKAGE = 'rMAFdb', table_name, text, header, rules, starting_point)
}

